version: '3.1'
services:
  wordpress:
    image: wordpress
    container_name: appgames
    restart: always
    ports:
      - 5023:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: senac
      WORDPRESS_DB_PASSWORD: 123@senac
      WORDPRESS_DB_NAME: gamestore
    volumes:
      - ~/gamestore/appgames:/var/www/html
  db:
    image: mysql:latest
    container_name: dbgames
    restart: always
    ports:
      - 6010:3306
    environment:
      MYSQL_DATABASE: gamestore
      MYSQL_USER: senac
      MYSQL_PASSWORD: 123@senac
      MYSQL_ROOT_PASSWORD: 123@senac
    volumes:
      - ~/gamestore/dbgames:/var/lib/mysql
